import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    './node_modules/flyonui/dist/js/*.js',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require('flyonui'),
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require('flyonui/plugin'),
  ],
  flyonui: {
    themes: [
      'dark',
      'light',
      'corporate',
      'gourmet',
      'luxury',
      'soft',
      {
        midnight: {
          'primary': '#38bdf8',
          'primary-content': '#001e33',
          'secondary': '#818cf8',
          'secondary-content': '#0f0f2e',
          'accent': '#34d399',
          'accent-content': '#00291d',
          'neutral': '#1e293b',
          'neutral-content': '#b8c4d0',
          'base-100': '#0f172a',
          'base-200': '#1e293b',
          'base-300': '#334155',
          'base-content': '#cbd5e1',
          'info': '#38bdf8',
          'success': '#4ade80',
          'warning': '#fbbf24',
          'error': '#fb7185',
        },
      },
      {
        emerald: {
          'primary': '#10b981',
          'primary-content': '#001a0e',
          'secondary': '#6ee7b7',
          'secondary-content': '#002a1a',
          'accent': '#fbbf24',
          'accent-content': '#1a1400',
          'neutral': '#1c2826',
          'neutral-content': '#b8cfc8',
          'base-100': '#0f1a17',
          'base-200': '#1c2826',
          'base-300': '#2a3b36',
          'base-content': '#d1e0da',
          'info': '#38bdf8',
          'success': '#4ade80',
          'warning': '#fbbf24',
          'error': '#fb7185',
        },
      },
      {
        crimson: {
          'primary': '#f43f5e',
          'primary-content': '#ffffff',
          'secondary': '#fb923c',
          'secondary-content': '#1a0800',
          'accent': '#facc15',
          'accent-content': '#1a1400',
          'neutral': '#2a2025',
          'neutral-content': '#d0b8c0',
          'base-100': '#1a1015',
          'base-200': '#2a2025',
          'base-300': '#3a3035',
          'base-content': '#e8d8e0',
          'info': '#38bdf8',
          'success': '#4ade80',
          'warning': '#fbbf24',
          'error': '#fb7185',
        },
      },
      {
        ocean: {
          'primary': '#6366f1',
          'primary-content': '#ffffff',
          'secondary': '#a78bfa',
          'secondary-content': '#0f0526',
          'accent': '#2dd4bf',
          'accent-content': '#002a25',
          'neutral': '#1e1b4b',
          'neutral-content': '#c4c1e0',
          'base-100': '#0c0a3e',
          'base-200': '#1e1b4b',
          'base-300': '#312e81',
          'base-content': '#ddd6fe',
          'info': '#38bdf8',
          'success': '#4ade80',
          'warning': '#fbbf24',
          'error': '#fb7185',
        },
      },
      {
        amber: {
          'primary': '#f59e0b',
          'primary-content': '#1a1400',
          'secondary': '#d97706',
          'secondary-content': '#1a1000',
          'accent': '#fbbf24',
          'accent-content': '#1a1400',
          'neutral': '#292524',
          'neutral-content': '#d6d3d1',
          'base-100': '#1c1917',
          'base-200': '#292524',
          'base-300': '#3a3735',
          'base-content': '#e7e5e4',
          'info': '#38bdf8',
          'success': '#4ade80',
          'warning': '#fbbf24',
          'error': '#fb7185',
        },
      },
      {
        slate: {
          'primary': '#94a3b8',
          'primary-content': '#0f172a',
          'secondary': '#64748b',
          'secondary-content': '#f1f5f9',
          'accent': '#e2e8f0',
          'accent-content': '#0f172a',
          'neutral': '#1e293b',
          'neutral-content': '#94a3b8',
          'base-100': '#0f172a',
          'base-200': '#1e293b',
          'base-300': '#334155',
          'base-content': '#e2e8f0',
          'info': '#38bdf8',
          'success': '#4ade80',
          'warning': '#fbbf24',
          'error': '#fb7185',
        },
      },
    ],
  },
} satisfies Config
